# Generated by Django 3.0.5 on 2020-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coliving_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
